# Generated by Django 4.2.6 on 2024-10-16 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Escheduler', '0003_shift_has_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='has_reported',
        ),
        migrations.AddField(
            model_name='employee',
            name='availability_days',
            field=models.CharField(default='Monday,Tuesday,Wednesday,Thursday,Friday', help_text="Comma-separated list of days (e.g., 'Monday,Tuesday')", max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='availability_end',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AddField(
            model_name='employee',
            name='availability_start',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shift',
            name='date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='shift',
            name='employees',
            field=models.ManyToManyField(blank=True, to='Escheduler.employee'),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(blank=True, choices=[('WD', 'Working Day'), ('WE', 'Weekend'), ('HD', 'Holiday')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Escheduler.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Escheduler.shift')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Escheduler.employee')),
                ('original_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_shift', to='Escheduler.shift')),
                ('requested_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_shift', to='Escheduler.shift')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
