# Generated by Django 4.2.6 on 2024-10-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escheduler', '0004_remove_employee_availability_remove_shift_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='report_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
