# Generated by Django 4.2.6 on 2024-10-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escheduler', '0005_shift_report_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftswaprequest',
            name='manager_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='reason',
            field=models.TextField(default='NO reason provided'),
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
