# Generated by Django 4.2.6 on 2024-10-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escheduler', '0007_timeoffrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(blank=True, choices=[('WD', 'Working Day'), ('WE', 'Weekend'), ('HD', 'Holiday')], max_length=20, null=True),
        ),
    ]
